[tool.poetry]
name = "YoiYoi Bot"
version = "4.6"
description = "This is a bot for downloading tiktok, twitter and instagram content."
authors = ["auorew <auuorew@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11,<3.12"
python-telegram-bot = {version = "^21.6", extras = ["job-queue", "webhooks"]}
python-dotenv = "^1.0.1"
sqlalchemy = "2.0.29"
alembic = "^1.13.3"
sqlalchemy-repr = "^0.1.0"
tzdata = "^2024.2"
python-magic = {version = "^0.4.27", platform = "linux"}
python-magic-bin = {version = "^0.4.14", platform = "win32"}
tenacity = "^9.0.0"
beautifulsoup4 = "^4.12.3"
pillow = "^11.0.0"
logtail-python = "^0.3.0"
pixivpy-async = "^1.2.14"
aiocache = "^0.12.0"
orjson = "^3.10.11"
snscrape = "^0.7.0.20230622"
python-dateutil = "^2.9.0.post0"
gallery-dl = "^1.27.7"
psycopg2-binary = "2.9.9"
yt-dlp = {version = "^2024.11.2.232942.dev0", allow-prereleases = true}
fastapi = "^0.115.0"
uvicorn = "^0.30.4"
pyrogram = "^2.0.106"
tgcrypto = "^1.2.5"
sqlalchemy-serializer = "^1.4.22"
httpx = {extras = ["socks"], version = "^0.27.0"}
pillow-heif = "^0.18.0"
pydantic-settings = "^2.6.1"

[tool.poetry.group.dev.dependencies]
isort = "^5.13.2"
black = "^24.10.0"
ruff = "^0.6.7"
pre-commit = "^4.0.1"
yesqa = "^1.5.0"

[tool.isort]
profile = "black"
skip = ["alembic.ini"]
skip_glob = [".*/", ".*", "log/", "*.log"]
line_length = 90
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
lines_between_types = 1

[tool.black]
line-length = 90
include = '\.pyi?$'

[tool.ruff]
select = ["E", "F"]
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
ignore = []
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
per-file-ignores = {}
line-length = 90
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
target-version = "py311"
