[file]
    enable = false
    # date format
    date = "%Y-%m-%d.%H-%M-%S"
    # folder path
    path = "log"
    # prefix for log file
    pref = "log."

[root]
    level = "DEBUG"
    form = "%(asctime)s [%(levelname)s] > %(name)s: %(message)s"

[root.file]
    level = "INFO"
    form = "%(asctime)s [%(levelname)s] > %(name)s: %(message)s"

[bot]
    level = "DEBUG"
    form = "%(asctime)s [%(levelname)s] > [%(update_id)s] %(name)s: %(message)s"

[bot.file]
    level = "INFO"
    form = "%(asctime)s [%(levelname)s] > [%(update_id)s] %(name)s: %(message)s"

[tail]
    level = "DEBUG"
    form = "%(message)s"

[tail.file]
    level = "DEBUG"
    form = "%(message)s"

# log library rules
[[lib]]
    # http requests
    name = "urllib3.connectionpool"
    enable = true
    level = "INFO"

[[lib]]
    # async caching
    name = "aiocache.base"
    enable = true
    level = "WARNING"

[[lib]]
    # http requests
    name = "httpx"
    enable = true
    level = "WARNING"

[[lib]]
    # http requests
    name = "httpcore"
    enable = true
    level = "WARNING"

[[lib]]
    # pyrogram dispatcher
    name = "pyrogram.dispatcher"
    enable = true
    level = "WARNING"

[[lib]]
    # pyrogram connection
    name = "pyrogram.connection"
    enable = true
    level = "WARNING"

[[lib]]
    # pyrogram session
    name = "pyrogram.session"
    enable = true
    level = "WARNING"

[[lib]]
    # SQL echoing
    name = "sqlalchemy.engine"
    enable = true
    level = "WARNING"

[[lib]]
    # connection pool logging
    name = "sqlalchemy.pool"
    enable = true
    level = "WARNING"

[[lib]]
    # custom logging for SQL dialects
    name = "sqlalchemy.dialects"
    enable = true
    level = "WARNING"

[[lib]]
    # logging of various ORM functions
    name = "sqlalchemy.orm"
    enable = true
    level = "WARNING"

[[lib]]
    # libvips vobject
    name = "pyvips.vobject"
    enable = true
    level = "INFO"

[[lib]]
    # libvips error
    name = "pyvips.error"
    enable = true
    level = "INFO"
